import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
// import 'package:i18n_extension/i18n_extension.dart';
import 'package:feather_icons/feather_icons.dart';
import 'package:awesome_bottom_bar/awesome_bottom_bar.dart';
import 'package:journo_blog/core/constansts/my_colors.dart';
import 'package:journo_blog/presentation/screens/general/add_post/add_post_imports.dart';
import 'package:journo_blog/presentation/screens/general/categories/categories_imports.dart';
import 'package:journo_blog/presentation/screens/general/home/home_imports.dart';
import 'package:journo_blog/presentation/screens/general/profile/profile_imports.dart';
import 'package:journo_blog/presentation/screens/general/tags/tags_imports.dart';
part 'general.dart';
part 'general_view_model.dart';
